// Code generated by swagger_to. DO NOT EDIT.
package product

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!

// No schemas are defined in the swagger.

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!
