// Code generated by swagger_to. DO NOT EDIT.
package product

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!

import (
	"errors"
	"fmt"
	"github.com/xeipuuv/gojsonschema"
)

func mustNewJSONSchema(text string, name string) *gojsonschema.Schema {
	loader := gojsonschema.NewStringLoader(text)
	schema, err := gojsonschema.NewSchema(loader)
	if err != nil {
		panic(fmt.Sprintf("failed to load JSON Schema %#v: %s", text, err.Error()))
	}
	return schema
}

var jsonSchemaEmptyParameterText = `{
  "title": "EmptyParameter",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "EmptyParameter": {
      "description": "defines an empty parameter.",
      "type": "object"
    }
  },
  "$ref": "#/definitions/EmptyParameter"
}`

var jsonSchemaWithEmptyPropertiesText = `{
  "title": "WithEmptyProperties",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "is a product detail.",
  "type": "object",
  "properties": {
    "required_empty_property": {},
    "optional_empty_property": {
      "type": "object"
    }
  },
  "required": [
    "required_empty_property"
  ]
}`

var jsonSchemaEmptyParameter = mustNewJSONSchema(
	jsonSchemaEmptyParameterText,
	"EmptyParameter")

var jsonSchemaWithEmptyProperties = mustNewJSONSchema(
	jsonSchemaWithEmptyPropertiesText,
	"WithEmptyProperties")

// ValidateAgainstEmptyParameterSchema validates a message coming from the client against EmptyParameter schema.
func ValidateAgainstEmptyParameterSchema(bb []byte) error {
	loader := gojsonschema.NewStringLoader(string(bb))
	result, err := jsonSchemaEmptyParameter.Validate(loader)
	if err != nil {
		return err
	}

	if result.Valid() {
		return nil
	}

	msg := ""
	for i, valErr := range result.Errors() {
		if i > 0 {
			msg += ", "
		}
		msg += valErr.String()
	}
	return errors.New(msg)
}

// ValidateAgainstWithEmptyPropertiesSchema validates a message coming from the client against WithEmptyProperties schema.
func ValidateAgainstWithEmptyPropertiesSchema(bb []byte) error {
	loader := gojsonschema.NewStringLoader(string(bb))
	result, err := jsonSchemaWithEmptyProperties.Validate(loader)
	if err != nil {
		return err
	}

	if result.Valid() {
		return nil
	}

	msg := ""
	for i, valErr := range result.Errors() {
		if i > 0 {
			msg += ", "
		}
		msg += valErr.String()
	}
	return errors.New(msg)
}

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!
