// Code generated by swagger_to. DO NOT EDIT.
package product

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!

import (
	"encoding/json"
	"github.com/gorilla/mux"
	"io/ioutil"
	"net/http"
)

// SetupRouter sets up a router. If you don't use any middleware, you are good to go.
// Otherwise, you need to maually re-implement this function with your middlewares.
func SetupRouter(h Handler) *mux.Router {
	r := mux.NewRouter()

	r.HandleFunc(`/test_endpoint`,
		func(w http.ResponseWriter, r *http.Request) {
			WrapTestEndpoint(h, w, r)
		}).Methods("get")

	return r
}

// WrapTestEndpoint wraps the path `/test_endpoint` with the method "get".
//
// Path description:
// test empty schema
func WrapTestEndpoint(h Handler, w http.ResponseWriter, r *http.Request) {
	var aRequiredEmptyParameter EmptyParameter

	if r.Body == nil {
		http.Error(w, "Parameter 'required_empty_parameter' expected in body, but got no body", http.StatusBadRequest)
		return
	}
	{
		var err error
		r.Body = http.MaxBytesReader(w, r.Body, 1024*1024)
		body, err := ioutil.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "Body unreadable: "+err.Error(), http.StatusBadRequest)
			return
		}

		err = ValidateAgainstEmptyParameterSchema(body)
		if err != nil {
			http.Error(w, "Failed to validate against schema: "+err.Error(), http.StatusBadRequest)
			return
		}

		err = json.Unmarshal(body, &aRequiredEmptyParameter)
		if err != nil {
			http.Error(w, "Error JSON-decoding body parameter 'required_empty_parameter': "+err.Error(),
				http.StatusBadRequest)
			return
		}
	}

	h.TestEndpoint(w,
		r,
		aRequiredEmptyParameter)
}

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!
