// Code generated by swagger_to. DO NOT EDIT.
package product

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!

// Capacity is an identifiable primitive definition.
type Capacity int32

// ProductSummary is a product summary object.
type ProductSummary struct {
	// is a test string property.
	ProductID string `json:"product_id"`

	Metadata interface{} `json:"metadata,omitempty"`

	Capacity *Capacity `json:"capacity,omitempty"`
}

// ProductDetail is a product detail
type ProductDetail struct {
	// is a test string property.
	ProductID string `json:"product_id"`

	Capacity *Capacity `json:"capacity,omitempty"`

	Metadata interface{} `json:"metadata"`

	Data interface{} `json:"data"`
}
