// Code generated by swagger_to. DO NOT EDIT.
package product

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!

// EmptyParameter defines an empty parameter.
type EmptyParameter struct{}

// WithEmptyProperties is a product detail.
type WithEmptyProperties struct {
	RequiredEmptyProperty interface{} `json:"required_empty_property"`

	OptionalEmptyProperty interface{} `json:"optional_empty_property,omitempty"`
}
