// Code generated by swagger_to. DO NOT EDIT.
package foo

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!

import "net/http"

// Handler defines an interface to handling the routes.
type Handler interface {
	// GetFoo handles the path `/` with the method "get".
	GetFoo(w http.ResponseWriter,
		r *http.Request)
}

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!
