// Code generated by swagger_to. DO NOT EDIT.
package foo

// Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!

type MyType struct {
	MyInteger *int32 `json:"my_integer,omitempty"`
}

type SubType struct {
	MyInteger *int32 `json:"my_integer,omitempty"`

	SubProperty *int32 `json:"sub_property,omitempty"`
}
